# Generated by Django 4.1.5 on 2023-02-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad_app', '0002_remove_todo_completed_todo_name_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='note',
            name='group',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
